// Jira write-back — the portal stops mirroring Jira and starts driving it:
//   · push generated acceptance criteria to the story as a comment
//   · create sub-tasks for 3 Amigos evaluator actions (owner-tagged)
//   · transition an issue through its workflow (e.g. To Do → In Progress)
// All calls use the same Basic-auth config as the read-side sync.

import type { JiraConfig } from './jira.js';

function authHeaders(cfg: JiraConfig): Record<string, string> {
  const auth = Buffer.from(`${cfg.email}:${cfg.apiToken}`).toString('base64');
  return { Authorization: `Basic ${auth}`, Accept: 'application/json', 'Content-Type': 'application/json' };
}

/** Plain text → minimal Atlassian Document Format (one paragraph per line). */
export function textToAdf(text: string): unknown {
  const lines = text.split('\n');
  return {
    type: 'doc',
    version: 1,
    content: lines.map((line) => ({
      type: 'paragraph',
      content: line.trim() === '' ? [] : [{ type: 'text', text: line }],
    })),
  };
}

export async function addJiraComment(
  cfg: JiraConfig,
  issueKey: string,
  text: string,
  fetchImpl: typeof fetch = fetch,
): Promise<{ id: string }> {
  const res = await fetchImpl(`${cfg.baseUrl}/rest/api/3/issue/${issueKey}/comment`, {
    method: 'POST',
    headers: authHeaders(cfg),
    body: JSON.stringify({ body: textToAdf(text) }),
  });
  if (!res.ok) throw new Error(`Jira comment failed for ${issueKey}: ${res.status} ${await res.text()}`);
  const body = (await res.json()) as { id: string };
  return { id: body.id };
}

export async function createJiraSubtask(
  cfg: JiraConfig,
  parentKey: string,
  summary: string,
  description: string,
  fetchImpl: typeof fetch = fetch,
): Promise<{ key: string }> {
  const projectKey = parentKey.split('-')[0];
  const res = await fetchImpl(`${cfg.baseUrl}/rest/api/3/issue`, {
    method: 'POST',
    headers: authHeaders(cfg),
    body: JSON.stringify({
      fields: {
        project: { key: projectKey },
        parent: { key: parentKey },
        issuetype: { name: 'Subtask' },
        summary: summary.slice(0, 240),
        description: textToAdf(description),
      },
    }),
  });
  if (!res.ok) throw new Error(`Jira sub-task creation failed under ${parentKey}: ${res.status} ${await res.text()}`);
  const body = (await res.json()) as { key: string };
  return { key: body.key };
}

/**
 * Transition an issue to the workflow status named `toStatus` (case-insensitive
 * match on the transition target). Throws with the available options when the
 * target isn't reachable from the current status.
 */
export async function transitionJiraIssue(
  cfg: JiraConfig,
  issueKey: string,
  toStatus: string,
  fetchImpl: typeof fetch = fetch,
): Promise<{ transitioned: string }> {
  const listRes = await fetchImpl(`${cfg.baseUrl}/rest/api/3/issue/${issueKey}/transitions`, {
    headers: authHeaders(cfg),
  });
  if (!listRes.ok) throw new Error(`Could not read transitions for ${issueKey}: ${listRes.status} ${await listRes.text()}`);
  const { transitions } = (await listRes.json()) as { transitions: { id: string; name: string; to?: { name?: string } }[] };

  const target = transitions.find(
    (t) => (t.to?.name ?? t.name).toLowerCase() === toStatus.toLowerCase(),
  );
  if (!target) {
    const available = transitions.map((t) => t.to?.name ?? t.name).join(', ') || 'none';
    throw new Error(`"${toStatus}" is not reachable from the current status of ${issueKey}. Available: ${available}`);
  }

  const doRes = await fetchImpl(`${cfg.baseUrl}/rest/api/3/issue/${issueKey}/transitions`, {
    method: 'POST',
    headers: authHeaders(cfg),
    body: JSON.stringify({ transition: { id: target.id } }),
  });
  if (!doRes.ok) throw new Error(`Transition failed for ${issueKey}: ${doRes.status} ${await doRes.text()}`);
  return { transitioned: target.to?.name ?? target.name };
}

/** Format AC scenarios as a readable Jira comment body. */
export function formatAcComment(
  scenarios: { title: string; kind: string; gherkin: { given: string; when: string; then: string } }[],
  source: string,
): string {
  const lines: string[] = [
    `Acceptance criteria generated by QE Intelligence Portal (source: ${source === 'ai' ? 'Claude AI' : 'deterministic template'})`,
    '',
  ];
  scenarios.forEach((s, i) => {
    lines.push(`${i + 1}. [${s.kind.toUpperCase()}] ${s.title}`);
    lines.push(`   Given ${s.gherkin.given}`);
    lines.push(`   When ${s.gherkin.when}`);
    lines.push(`   Then ${s.gherkin.then}`);
    lines.push('');
  });
  return lines.join('\n').trimEnd();
}
